runtime: python310  # Or another suitable runtime (e.g., nodejs18, go120, php82, etc.)
instance_class: F1  # Or another instance class (e.g., B1, B2, B4, F2, F4_1G) - choose based on your needs
automatic_scaling:  # Or manual_scaling - see below for manual scaling configuration
  min_idle_instances: 1  # Minimum number of idle instances
  max_idle_instances: automatic # Recommended: let App Engine manage this
  min_pending_latency: 30ms # Target latency for new instances
  max_pending_latency: automatic # Recommended: let App Engine manage this
  max_concurrent_requests: 50 # Maximum concurrent requests per instance

# Manual scaling (alternative to automatic_scaling):
# manual_scaling:
#   instances: 2  # Fixed number of instances

handlers:
- url: /.*
  script: auto  # Use this for most frameworks (Flask, Django, etc.)
  secure: always  # Enforce HTTPS

# Optional settings:
env_variables:
  MY_VARIABLE: my_value  # Set environment variables

# For specific frameworks, add framework-specific configuration here:
# Example for Flask:
# entrypoint: gunicorn -b :$PORT main:app

# Example for Django:
# entrypoint: gunicorn --bind :$PORT myproject.wsgi

# Example for a static website:
# handlers:
# - url: /
#   static_dir: static

# Error handlers:
error_handlers:
- file: 404.html # Custom 404 error page
  error_code: 404
- file: 500.html # Custom 500 error page
  error_code: default

# Specify the service name if you are using multiple services:
# service: my-service-name